receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
processors:
extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
    logs:
      receivers: [otlp]
      exporters: [otlp, logging]
  extensions: [memory_ballast, zpages, health_check]
