apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springwebflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springwebflux
  template:
    metadata:
      labels:
        app: java-springwebflux
    spec:
      containers:
        - name: java-springwebflux
          image:  tracing-demo-java-springwebflux
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka.default.svc.cluster.local:9092
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://otel-collector:4318/v1/logs"
            - name: OTEL_SERVICE_NAME
              value: "java-spring-webflux"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-springwebflux
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java-springwebflux
