apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-rest
  template:
    metadata:
      labels:
        app: quarkus-rest
    spec:
      containers:
        - name: quarkus-rest
          image: tracing-demo-quarkus-rest
          imagePullPolicy: IfNotPresent
          env:
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
          ports:
            - containerPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-rest
spec:
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    app: quarkus-rest
