apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      labels:
        app: jaeger-all-in-one
    spec:
      containers:
        - name: jaeger-all-in-one
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
spec:
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
    - name: collector-http
      port: 14268
      targetPort: 14268
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: otel
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger-all-in-one
